### ISSUE TITLE
want to know from where  the message receive is initiated after send button is pressed how does the tinode bot reply ? 

### ISSUE THREAD

**Issue by vatsal78** [tinode/android-example#5]

**Comment by vatsal78** [comment]
Exactly i want to know the point where messages are received.. like if i send "hi" message that can be found from send message() function.The reply for that chat is done by Tino the bot, so from which function the reply messages are shown in the chat. like function which awaits reply or where i can see what is the reply and accordingly i can alter the message before it is received by the user

**Comment by or-else** [comment]
Received by the server from the client? From client by the server? By The chatbot from the server? From the socket? From the channel? Processed? You have to ask more specific questions otherwise it's not very productive. Your question about the chatbot is answered in my previous reply but you did not respond to my answers so I don't know if that's what you are looking for or not. You may also want to describe your use case and I'll try to figure out what you want.

Please do your homework and try to be more specific. Thanks.
